In [1]:
#Script for cleaning games.csv file inside reosurces folder
#Developed by Cesar Isaac Diaz Crespo

#importing dependencies
import os
import pandas as pd
import numpy as np

In [2]:
#Files Path
input_file = os.path.join("..","Resources","games.csv")
output_file = os.path.join("..","Clean_Data","games.csv")

In [3]:
#Reading csv file into a dataframe
games_df = pd.read_csv(input_file)

games_df = games_df.loc[games_df["gameDate"]>='2010']
games_df = games_df[games_df.seasonType.isin(['REG','POST','SB'])]
#games_df['seasonType'].value_counts()
games_df.head()

FileNotFoundError: [Errno 2] File b'..\\Sources\\games.csv' does not exist: b'..\\Sources\\games.csv'

In [53]:
#Creating a new DataFrame only with needed columns
games_df = games_df[["gameId","season","gameDate","homeTeamId","visitorTeamId","seasonType","winningTeam"]]
games_df.head()

    gameId  season    gameDate seasonType  winningTeam
65   55504    2012  2012-09-05        REG         1200
66   55508    2012  2012-09-09        REG         2120
67   55509    2012  2012-09-09        REG          200
68   55510    2012  2012-09-09        REG         3000
69   55505    2012  2012-09-09        REG          810

In [54]:
#Cleaning the data
games_df = games_df.astype({"gameDate":"str"})
games_df = games_df.astype({"seasonType":"str"})
games_df

      gameId  season    gameDate seasonType  winningTeam
65     55504    2012  2012-09-05        REG         1200
66     55508    2012  2012-09-09        REG         2120
67     55509    2012  2012-09-09        REG          200
68     55510    2012  2012-09-09        REG         3000
69     55505    2012  2012-09-09        REG          810
...      ...     ...         ...        ...          ...
2647   58163    2019  2020-01-12       POST         1800
2648   58162    2019  2020-01-12       POST         2310
2649   58164    2019  2020-01-19       POST         2310
2650   58165    2019  2020-01-19       POST         4500
2651   58167    2019  2020-02-02       POST         2310

[2086 rows x 5 columns]

In [55]:
#Sending the data to csv file
games_df.to_csv(output_file,index=False,header=True)